[package]
name = "actix_app"
version = "0.1.0"
edition = "2018"
authors = ["Alex Wolf github@mail.alexanderwolf.io"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
env_logger = "0.10.0"
